### PR TITLE
Update pattern 2.6.1

### PR DESCRIPTION
**Pull request by cosmo0920**
I noticed that logstash grok parser updates grok patterns.
`JAVACLASS` and `JAVAFILE` were duplicated and removed.
I believe that we can simply bump patch version.
Could you kindly take a look, @okkez?

### CODE REVIEW

**Comment by okkez** [comment]
Thanks.

**Comment by okkez** [comment]
Could you release new version?

**Comment by cosmo0920** [comment]
I wish I could do it. But I don't have push permission in this repository. 😰

**Comment by okkez** [comment]
@repeatedly Could you add push permission to @cosmo0920 ?

**Comment by repeatedly** [comment]
Added.

**Comment by cosmo0920** [comment]
Thanks. I've released this change as v2.6.1.

**Pull request merged**
